-- 모든 테이블과 시퀀스 초기화
DROP TABLE REVIEW;
DROP TABLE RESERVATION;
DROP TABLE PACKAGE;
DROP TABLE GUIDE;
DROP TABLE CUSTOMER;

DROP SEQUENCE CUSTOMER_SEQ;
DROP SEQUENCE GUIDE_SEQ;
DROP SEQUENCE PACKAGE_SEQ;
DROP SEQUENCE RESERVATION_SEQ;
DROP SEQUENCE REVIEW_SEQ;


-- 고객 테이블 -----------------------------------------------------
CREATE TABLE CUSTOMER(
    NO NUMBER, -- PK 
    NAME VARCHAR2(50) NOT NULL,
    BIRTH VARCHAR2(30) NOT NULL, -- 20011217 형태로 입력
    NATIONAL VARCHAR2(20) NOT NULL,
    GENDER VARCHAR2(10) NOT NULL, --  CHECK(남자, 여자)
    EMAIL VARCHAR2(40) NOT NULL,
    PHONE VARCHAR2(15) NOT NULL
);    
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_NO_PK PRIMARY KEY(NO);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_GENDER_CHECK CHECK (GENDER IN ('남자', '여자'));

-- 고객 테이블의 NO(PK)의 자동 시퀀스
CREATE SEQUENCE CUSTOMER_SEQ
START WITH 1
INCREMENT BY 1;


-- 가이드 테이블 -------------------------------------------------------
CREATE TABLE GUIDE (
    NO NUMBER, -- PK
    NAME VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(15) NOT NULL,
    LANGUAGE VARCHAR2(40) NOT NULL
);
ALTER TABLE GUIDE ADD CONSTRAINT GUIDE_NO_PK PRIMARY KEY(NO);


-- 가이드 테이블의 NO(PK)의 자동 시퀀스
CREATE SEQUENCE GUIDE_SEQ
START WITH 1
INCREMENT BY 1;


-- 여행상품 테이블 -------------------------------------------------
CREATE TABLE PACKAGE (
    NO NUMBER, --PK
    NAME VARCHAR2(50) NOT NULL,
    NATIONAL VARCHAR2(20) NOT NULL,
    PRICE NUMBER NOT NULL,
    GUIDE_NO NUMBER, --FK
    SDATE DATE DEFAULT SYSDATE,
    EDATE DATE DEFAULT SYSDATE
--    AMOUNT NUMBER NOT NULL -- 여행 상품 수량 
);
ALTER TABLE PACKAGE ADD CONSTRAINT PACKAGE_NO_PK PRIMARY KEY (NO); 
ALTER TABLE PACKAGE ADD CONSTRAINT PACKAGE_GUIDE_NO_FK 
    FOREIGN KEY (GUIDE_NO) REFERENCES GUIDE(NO) ON DELETE CASCADE;
 
-- 여행상품 테이블의 NO(PK)의 자동 시퀀스
CREATE SEQUENCE PACKAGE_SEQ
START WITH 1
INCREMENT BY 1;


-- 예약 테이블 --------------------------------------------------------------
CREATE TABLE RESERVATION(
    NO NUMBER, --PK
    CUST_NO NUMBER, --FK
    PACK_NO NUMBER, --FK
    METHOD VARCHAR2(20) NOT NULL,
    RDATE DATE DEFAULT SYSDATE
);
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_NO_PK PRIMARY KEY (NO);
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_CUST_NO_FK 
    FOREIGN KEY(CUST_NO) REFERENCES CUSTOMER(NO) ON DELETE CASCADE;
Alter table RESERVATION ADD CONSTRAINT RESERVATION_PACK_NO_FK 
    FOREIGN KEY(PACK_NO) REFERENCES PACKAGE(NO) ON DELETE CASCADE;   
       
-- 예약 테이블의 NO(PK)의 자동 시퀀스       
CREATE SEQUENCE RESERVATION_SEQ
START WITH 1
INCREMENT BY 1;


-- 리뷰 테이블 ----------------------------------------------------------------
CREATE TABLE REVIEW(
    NO NUMBER, --PK
    RESERV_NO NUMBER, --FK
    GUIDE_REVIEW NUMBER(2) NOT NULL,
    SCHE_REVIEW NUMBER(2) NOT NULL,
    AVG_REVIEW NUMBER(3, 1)
);
ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_NO_PK PRIMARY KEY (NO);
ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_RESERV_NO_FK 
    FOREIGN KEY(RESERV_NO) REFERENCES RESERVATION(NO) ON DELETE CASCADE;   
  
-- 리뷰 테이블의 NO(PK)의 자동 시퀀스  
CREATE SEQUENCE REVIEW_SEQ
START WITH 1
INCREMENT BY 1;

COMMIT;


--=============================================================================================
-- 리뷰의 평균값 구하는 트리거
CREATE OR REPLACE TRIGGER REVIEW_TRIGGER
BEFORE INSERT OR UPDATE ON REVIEW
FOR EACH ROW
BEGIN
    IF :NEW.GUIDE_REVIEW IS NOT NULL AND :NEW.SCHE_REVIEW IS NOT NULL THEN
        :NEW.AVG_REVIEW := (:NEW.GUIDE_REVIEW + :NEW.SCHE_REVIEW) / 2;
    ELSE
        -- 기본값 설정
        :NEW.AVG_REVIEW := 0;
    END IF;
END;
/

